var token1 = 'WFC';
 

export const l = {
  token1:token1,
  h_n1 : "Home",
  h_n3 : "Swap",
  h_n4 : "Farm",
  h_n5 : "DAO",
  h_n6: "Ranking",
  home_n1: "TVL",
  home_n2: "DOP Price",
  home_n3: "WFC Price",
  cwallet: "Connect Wallet",
  langtype: "简体中文",
  reward: 'Harvest',
  nhsyl: "APY",
  deposited: "Your Locked",
  VL: "Total Locked",
  lockDay: "Lock Period",
  days: "days",
  goLock: "Lock "+token1,
  back: "BACK",
  totalLock: "Total Locked",
  rcl: token1+" Daily Rewards",
  deposit1: "Deposit",
  withdrawal1: "Withdraw",
  wbalance: token1+" Wallet Balance: ",
  avaliable: token1+" Awards: ",
  noLock: "Unlocked position",
  lockTime: "Unlock time：",
  myLocked: "My Locked:",
  max: "Max",
  bt_t: "Notice:",
  bt_1_1: "1. Lock your "+ token1 +" to receive ",
  bt_1_2: " for staking.",
  bt_2_1: "2. Once locked, the pledged token will take ",
  bt_2_2: " days to withdraw;",
  bt_3_1: "3. Each time a new lock is performed, the unlock date will be recalculated based on the weighted average with the number of unstaked ",
  bt_3_2: ".",
  bt_4: "4. Each time you stake&unstake your fToken, your "+token1+" will be auto-transferred to your wallet.",

  yesterday: "YesterDay",
  today: "Today",
  week: "Week",
  month: "Month",
  ranking_t: "Dividend amount ranking",
  ranking_t1: "Ranking",
  ranking_t2: "Address",
  ranking_t3: "Dividend amount",
  nodata: "No data",
  ranking_tips1: "The top 50 dividends will receive 249 "+token1+" in proportion",
  ranking_tips2: "The top 50 dividends will receive 1743 "+token1+" in proportion",
  ranking_tips3: "The top 50 dividends will receive 7290 "+token1+" in proportion",

  withdrawal: "Withdrawal",
  approve: "Approve",
  sygz: "Income",
  claim: "CLAIM",
  withdrawall: "Withdraw All",
  iptPlace: "Enter Amount",
  deposit: "Deposit",
  depositall: "Deposit All",
  balance: "Balance",
  menu1: "Home",
  menu2: "Vault",
  home_t1: "Single Farms",
  home_t2: "LP Farms",
  home_seemore: "View More",
  mining: "Mining",
  home_icon1_text: "High Yield",
  home_icon2_text: "Smart Matching",
  home_icon3_text: "Risk Hedging",
  home_icon4_text: "Withdraw Anytime",

  all: 'ALL',
  my: 'MY',

  approve_ok: "Approve Success,please retry!",
  start: "Start",
  partner: "Partners",
  sjjg: "Audit Institution",
  f_lv: "APR",
  op_wk: "farm",
  fmd_op1: "Claim Rewards",
  fmd_op2: "Exit: Claim & Unstake",
  error_tips_unconnect: "Please open MetaMask,connect your account!",
  error_tips_num0: "You must input a value greater than 0",
  error_tips_claim: "You have no claimable rewards",
  error_tips_trans: "You have nothing to transmute",
  ok_tips_deposit: "Deposit success!",
  ok_tips_withdraw: "Withdrawal success!",
  ok_tips_claim: "Claim Rewards success!",
  ok_tips_claim_exit: "Exit: Claim & Unstake success",
  notmainnet_title: "Warning",
  notmainnet_tips: "You're viewing data not from the main networks, please connected to the main network.",
  no_main_tips: "Network Error,Please make sure you connect to the BSC mainnet!",
  no_metamask_tips: "You have not installed the MetaMask wallet plugin!",
  catch_err: "Network Anomaly",
  footer1 : 'Audit',
  sjurl: 'https://wfcbsc.com/depfilm/audit.pdf',
  footer2 : 'Twitter',
  footer3 : 'Telegrame',
  lp: "LP Farm",
  db: "Single Coin Farm",
  invite_text: "My invitation link",

  //nft
  enterNUm: "please enter NFT number",
  buy: "Buy",
  num: "Number:",
  price: "Price(WFC):",
  s_all: "All",
  s_sale: "Sale",
  s_unsale: "Banned",
  s_status: "Status:",
  sale_price: "Sale Price(WFC)",
  saleBack: "Repurchase",
  setSale: "Set as sellable",
  setUnsale: "Set as unsellable",
  go: "Go",
  prev: "Prev",
  next: "Next",
  operate_ok: "Operate Success!",
  number_error: "Please enter right number!",
  no_nft: "You don’t have NFT yet, please buy it first!",
  no_own: "You don’t have an NFT with this number, please go to all to check！",
  price_error: "Please enter right price！"
}