var token1 = 'WFC';
 

export const l = {
  t_isbottom:'bottom line',
  t_loadMore:'click it load more',
  t_loading:'loading...',
  t_MinPA:'Minimun Amount',
  t_Price:'Price',
  t_to:'To',
  t_from:'From',
  t_Duic:'for',
  t_SWAP:'SWAP',
  t_approving:'approvaling...',
  t_cuntip:'Deposit currency ratio',
  t_value:'Money',
  t_home3:'to help users achieve higher returns.',
  t_home2:'find high-yielding projects within multiple DeFi protocols',
  t_home1:'Support multiple DeFi protocols.',
  t_tre:'Total revenue',
  t_ttt:'Total deposit',
  t_num:'Number',
  t_info:'Team Information',
  t_desc1:'The proportion of team income that can be enjoyed by reaching the level is ',
  t_desc:'Team deposit required',
  t_todayp:'Earnings today',
  t_tolp:'Total market revenue',
  t_abd:'Swap Details',
  t_wde:'Withdrawel Details',
  t_depD:'Deposit Details',
  t_profitD:'Profit Details',
  t_int:'Invite',
  t_de:'detail',
  t_tolIn:'Total Income',
  t_tolOut:'Total Takeout',
  t_jiedata:'Settlement date',
  t_dedata:'Transaction date',
  t_transA:'withdrawal',
  t_withdrawel:'withdrawal',
  t_totalWith:'Total withdrawal',
  t_servicege:'Service charge description',
  t_transamount:'Transaction amount',
  t_transdate:'Transaction date',
  t_deposit:'deposit',
  t_profit:'Total market revenue',
  e_today:'Earnings Today',
  t_level:'Team Level',
  w_cnt:'Connect Wallet',
  w_scnt:'Wallet is connected',
  i_invite:'Invite',
  t_team:'Team',
  token1:token1,
  h_n1 : "Home",
  h_n2 : "Farm",
  h_n3 : "Swap",
  h_n4 : "Market",
  h_n5 : "My",
  h_n6: "Ranking",
  home_n1: "TVL",
  home_n2: "DOP Price",
  home_n3: "LBR Price",
  cwallet: "Connect Wallet",
  langtype: "简体中文",
  reward: 'Harvest',
  nhsyl: "APY",
  deposited: "Your Locked",
  VL: "Total Locked",
  lockDay: "Lock Period",
  days: "days",
  goLock: "Lock "+token1,
  back: "BACK",
  totalLock: "Total Locked",
  rcl: token1+" Daily Rewards",
  deposit1: "Deposit",
  withdrawal1: "Withdraw",
  wbalance: token1+" Wallet Balance: ",
  avaliable: token1+" Awards: ",
  noLock: "Unlocked position",
  lockTime: "Unlock time：",
  myLocked: "My Locked:",
  max: "Max",
  bt_t: "Notice:",
  bt_1_1: "1. Lock your "+ token1 +" to receive ",
  bt_1_2: " for staking.",
  bt_2_1: "2. Once locked, the pledged token will take ",
  bt_2_2: " days to withdraw;",
  bt_3_1: "3. Each time a new lock is performed, the unlock date will be recalculated based on the weighted average with the number of unstaked ",
  bt_3_2: ".",
  bt_4: "4. Each time you stake&unstake your fToken, your "+token1+" will be auto-transferred to your wallet.",

  yesterday: "YesterDay",
  today: "Today",
  week: "Week",
  month: "Month",
  ranking_t: "Dividend amount ranking",
  ranking_t1: "Ranking",
  ranking_t2: "Address",
  ranking_t3: "Dividend amount",
  nodata: "No data",
  ranking_tips1: "The top 50 dividends will receive 249 "+token1+" in proportion",
  ranking_tips2: "The top 50 dividends will receive 1743 "+token1+" in proportion",
  ranking_tips3: "The top 50 dividends will receive 7290 "+token1+" in proportion",

  withdrawal: "Withdrawal",
  approve: "Approve",
  sygz: "Income",
  claim: "CLAIM",
  withdrawall: "Withdraw All",
  iptPlace: "Enter Amount",
  deposit: "Deposit",
  depositall: "Deposit All",
  balance: "Balance",
  menu1: "Home",
  menu2: "Vault",
  home_t1: "Single Farms",
  home_t2: "LP Farms",
  home_seemore: "View More",
  mining: "Mining",
  home_icon1_text: "High Yield",
  home_icon2_text: "Smart Matching",
  home_icon3_text: "Risk Hedging",
  home_icon4_text: "Withdraw Anytime",

  all: 'ALL',
  my: 'MY',

  approve_ok: "Approve Success,please retry!",
  start: "Start",
  partner: "Partners",
  sjjg: "Audit Institution",
  f_lv: "APR",
  op_wk: "farm",
  fmd_op1: "Claim Rewards",
  fmd_op2: "Exit: Claim & Unstake",
  error_tips_unconnect: "Please open MetaMask,connect your account!",
  error_tips_num0: "You must input a value greater than 0",
  error_tips_claim: "You have no claimable rewards",
  error_tips_trans: "You have nothing to transmute",
  ok_tips_deposit: "Deposit success!",
  ok_tips_withdraw: "Withdrawal success!",
  ok_tips_claim: "Claim Rewards success!",
  ok_tips_claim_exit: "Exit: Claim & Unstake success",
  notmainnet_title: "Warning",
  notmainnet_tips: "You're viewing data not from the main networks, please connected to the main network.",
  no_main_tips: "Network Error,Please make sure you connect to the BSC mainnet!",
  no_metamask_tips: "You have not installed the MetaMask wallet plugin!",
  catch_err: "Network Anomaly",
  footer1 : 'Audit',
  sjurl: 'https://wfcbsc.com/depfilm/audit.pdf',
  footer2 : 'Twitter',
  footer3 : 'Telegrame',
  lp: "LP Farm",
  db: "Single Coin Farm",
  invite_text: "My invitation link",

  //nft
  enterNUm: "please enter NFT number",
  buy: "Buy",
  num: "Number:",
  price: "Price(WFC):",
  s_all: "All",
  s_sale: "Sale",
  s_unsale: "Banned",
  s_status: "Status:",
  sale_price: "Sale Price(WFC)",
  saleBack: "Repurchase",
  setSale: "Set as sellable",
  setUnsale: "Set as unsellable",
  go: "Go",
  prev: "Prev",
  next: "Next",
  operate_ok: "Operate Success!",
  number_error: "Please enter right number!",
  no_nft: "You don’t have NFT yet, please buy it first!",
  no_own: "You don’t have an NFT with this number, please go to all to check！",
  price_error: "Please enter right price！",

  Slippage_tolerance:'Slippage tolerance',
  Transaction_deadline:'Transaction deadline',
  minute_swap:'minutes',
  Interface_Settings:'Interface Settings',
  Toggle_Audio_Mode:'Toggle Audio Mode',
  swap_on:'On',
  swap_off:'Off',



  l_copy:'Copy successfully',
  l_copyf:'Copy failed, please try again!',
  l_upper:'The parent address does not exist',
  l_addrror:'The connected wallet address is the same as the upper-level address',
  l_numerror:'input num error',
  l_stockvalue:'Deposit deposit value must be greater than $100',
  l_noprofit:'Currently you have no income to withdraw',
  l_unprofit:'Income balance',
  l_unfinished:'Undone',
  l_completed:'Completed',
  l_teamlink:'team link',
  l_noTeamBelowInfo:'No subordinate information for this team',
  t_tolOne:'Total',
  l_deposit_desc:'Deposit can add value',
  l_sureIt:'Confirm',
  l_konwIt:'Got it',
  l_widthing:'withdrawing',
  l_innering:'depositing',
  l_duiing:'confirming',
  l_numing:'number',
  l_you:'You will get',
  l_maxa:'Max',
  l_ming:'Detail',
}