const token1 = ''
export const l = {
  t_isbottom:'それは底です',
  t_loadMore:'クリックしてさらにロード',
  t_loading:'読み込み中...',
  t_MinPA:'最小量',
  t_Price:'価格',
  t_to:'to',
  t_from:'from',
  t_Duic:'Exchange',
  t_SWAP:'トランザクション',
  t_approving:'承認...',
  t_cuntip:'預金比率',
  t_value: 'amount',
  t_home3: 'ユーザーがより高い収益を得るのを助けます。 ',
  t_home2: '「複数のDeFi契約で見つかった高利回りプロジェクト」',
  t_home1:  '複数のDeFiプロトコルをサポートします。 ', 
  t_tre: '「チームのメリット」', 
  t_ttt:  'チームパフォーマンス', 
  t_num:  'チームメンバーの数', 
  t_info:  'チーム情報', 
  t_desc1:  'このレベルに到達することで享受できるチーム収益の割合は', 
  t_desc: '「チームのパフォーマンスが必要」', 
  t_todayp: '「今日の収益」', 
  t_tolp:  '総収入', 
  t_abd:  'トランザクションレコード', 
  t_wde:  'レコードの抽出', 
  t_depD:  '記録に保存', 
  t_profitD:  '利益記録', 
  t_int:  '招待', 
  t_tolIn:  '総収入', 
  t_tolOut:  '総抽出', 
  t_tolOne:  '合計', 
  t_de:  '詳細', 
  t_jiedata:  '決済日', 
  t_dedata:  '入金時間', 
  t_withdrawel:  '撤回', 
  t_totalWith:  '合計引き出し', 
  t_servicege:  '手数料', 
  t_transA:  '数量の抽出', 
  t_transamount:  '取引金額', 
  t_transdate:  '取引日', 
  t_deposit:  'デポジット量', 
  t_profit:  '総市場利益', 
  e_today: '「今日の収益」', 
  t_level:  'チームレベル', 
  w_cnt:  'ウォレットを接続します', 
  w_scnt:  'ウォレットが接続されています', 
  i_invite:  'invite', 
  t_team:  'チーム', 
  token1: token1, 
  h_n1: '「ホームページ」', 
  h_n2: '「マイニング」', 
  h_n3:  "Exchange", 
  h_n4: '「市場」', 
  h_n5: '「私の」', 
  h_n6: 'リーダーボード', 
  home_n1:  "合計ロックアップ量", 
  home_n2:  "DOP価格", 
  home_n3:  "LBR価格", 
  cwallet:  "Connect Wallet", 
  langtype:  "英語", 
  reward: '「収穫」',
  nhsyl: "「年間収益率」",
  deposited: "「あなたのロックされた位置」",
  VL: "「トータルロックアップ」",
  lockDay: "ロックアップ期間」",
  days: "「天」",
  goLock: "「ウェアハウスのロック」 "+token1,
  back: "「戻る」",
  totalLock: "合計ロック位置",
  rcl: token1+"日次出力",
  deposit1: "「預金コイン",
  withdrawal1: "「撤回」",


  withdrawal: "「引き出し",
  approve: "「承認」",
  sygz: "「利益",
  claim: "「引き出し収入」",
  withdrawall: "「すべて撤回」",
  iptPlace: "数量を入力",
  deposit: "「デポジット」",
  depositall: "「すべてデポジット」",
  balance: "「バランス」",
  menu1: "「ホーム」",
  menu2: "「機関銃プール」",
  home_t1: "「単一通貨の誓約マイニング」",
  home_t2: "「LPプレッジマイニング」",
  home_seemore: "もっと見る",
  mining: "「Goto mine」",
  home_icon1_text: "高利回り",
  home_icon2_text: "スマートマッチング",
  home_icon3_text: "リスクヘッジ",
  home_icon4_text: "保存して取得",


  all: '「すべて」',
  my: '「私の」',

  start: "「開始」",
  partner: "「パートナー」",
  approve_ok: '「認証は成功しました。続行してください！」', 
  f_lv:  "APR", 
  op_wk:  "マイニング", 
  fmd_op1:  "報酬を受け取る", 
  fmd_op2:  "終了: 報酬の受け取りとロック解除", 
  error_tips_unconnect:  "MetaMaskウォレットを開いて, アカウントを接続してください！", 
  error_tips_num0:  "0より大きい数値を入力する必要があります！", 
  more_than_deposit:  "引き出された金額は, 入金された金額よりも多いです！", 
  error_tips_claim: '「請求する報酬はありません！」', 
  error_tips_trans:  "変換可能なトークンがありません！", 
  ok_tips_deposit:  "デポジットは成功しました！", 
  ok_tips_withdraw:  "正常に抽出されました！", 
  ok_tips_claim: '「報酬を正常に請求してください！」', 
  ok_tips_claim_exit:  "終了: 報酬の請求とリリース", 
  notmainnet_title:  "警告", 
  notmainnet_tips:  "現在閲覧しているデータはメインネットワークからのものではありません。ウォレットをメインネットワークに切り替えてください！", 
  no_main_tips: '「ネットワークエラー。BSCメインネットに接続していることを確認してください！」', 
  no_metamask_tips:  "MetaMaskウォレットプラグインをインストールしていません！", 
  catch_err:  "ネットワーク例外", 
  footer1: '「監査」', 
  sjurl:  'https: //wfcbsc.com/depfilm/audit.pdf', 
  footer2: '「Twitter」', 
  footer3: '「テレグラム」', 
  lp: '「LPマイニング」', 
  db: '「単一通貨マイニング」', 
  invoke_text:  "リンクを招待", 
  
  
  enterNUm: '「番号を入力してください」', 
  buy: '「購入」', 
  num:  "Number: ", 
  price: '「価格（WFC）: 」', 
  s_all:  "すべて", 
  s_sale:  "販売可能", 
  s_unsale:  "Unsale", 
  s_status:  "ステータス: ", 
  sale_price:  "販売価格（WFC）", 
  saleBack: '「買い戻し」', 
  setSale:  "販売可能として設定", 
  setUnsale:  "Set Unsale", 
  go: '「ジャンプ」', 
  prev: '「前のページ」', 
  next: '「次のページ」', 
  Operate_ok:  "操作は成功しました！", 
  number_error:  "正しい番号を入力してください！", 
  no_nft: '「まだNFTをお持ちではありません。最初に購入してください！」', 
  no_own: '「この番号のNFTをお持ちではありません。すべてチェックインしてください！」', 
  price_error:  "正しい価格を入力してください！", 

  Slippage_tolerance:  '変位許容値', 
  Transaction_deadline:  'トランザクションの期限', 
  minutes_swap:  '分', 
  Interface_Settings:  'インターフェイス設定', 
  Toggle_Audio_Mode:  'オーディオモードの切り替え', 
  swap_on:  'on', 
  swap_off:  'オフ', 

  l_copy:  'コピー成功', 
  l_copyf:  'コピーに失敗しました。もう一度やり直してください。 ', 
  l_upper:  '上位アドレスが存在しません', 
  l_addrror:  '接続されたウォレットアドレスは上位レベルのアドレスと同じです', 
  l_numerror:  '入力数量が間違っています', 
  l_stockvalue:  '預金額は100米ドルを超えている必要があります', 

  l_noprofit:  '現在, 撤回する利益はありません', 
  l_unprofit:  '上げることができます', 
  l_unfinished:  'unfinished', 
  l_completed:  '完了', 
  l_teamlink:  '検索リンク', 
  l_enterrightaddress:  '正しいウォレットアドレスを入力してください', 
  l_noTeamBelowInfo:  'このチームの下位情報はありません', 
  l_deposit_desc:'預金は価値を付加できる',
  l_sureIt:'確認',
  l_konwIt:'とった',
  l_widthing:'抽出',
  l_innering:'デポジットイン',
  l_duiing:'確認中',
  l_numing:'number',
  l_you:'「あなたは得るでしょう」',
  l_maxa:'Max',
  l_ming:'詳細',
  l_swapt:'償還の確認',
  l_swapm:`トランザクションが出力された場合、少なくとも{0}{1}を受け取ります。それ以外の場合、トランザクションは再開されます。`,
  l_next:'Next',
  l_swaps:'{0} {1}を使用して{2} {3}を交換します',
  l_swapb:'ウォレットでのトランザクションの確認',
  l_success:'提出された',
  swap_setting:'スワップ設定',
  l_invite:'招待',


  l_error_upper:'上位アドレスが正しくありません',
}