var token1 = 'Libra';


export const l = {
  t_isbottom:'바닥이다',
  t_loadMore:'더 로드하려면 클릭',
  t_loading:'로드 중...',
  t_MinPA:'최소 금액',
  t_Price:'가격',
  t_to:'~에',
  t_from:'from',
  t_Duic:'교환',
  t_SWAP:'거래',
  t_approving:'승인...',
  t_cuntip:'예금 비율',
  t_value:'금액',
  t_home3:'사용자가 더 높은 수익을 얻을 수 있도록 도와주세요. ',
  t_home2:'여러 DeFi 계약에서 발견된 고수익 프로젝트',
  t_home1:'여러 DeFi 프로토콜을 지원합니다. ',
  t_tre:'팀 혜택',
  t_ttt:'팀 성과',
  t_num:'팀원 수',
  t_info:'팀 정보',
  t_desc1:'이 레벨에 도달하여 누릴 수 있는 팀 수익의 비율은',
  t_desc:'팀 성과 필요',
  t_todayp:'오늘의 수입',
  t_tolp:'총 수익',
  t_abd:'거래 기록',
  t_wde:'레코드 추출',
  t_depD:'기록에 저장',
  t_profitD:'이익 기록',
  t_int:'초대',
  t_tolIn:'총 수입',
  t_tolOut:'총 추출',
  t_tolOne:'전체',
  t_de:'세부정보',
  t_jiedata:'결제일',
  t_dedata:'입금 시간',
  t_withdrawel:'철회',
  t_totalWith:'총 인출',
  t_servicege:'취급 수수료',
  t_transA:'추출량',
  t_transamount:'거래 금액',
  t_transdate:'거래 날짜',
  t_deposit:'입금 수량',
  t_profit:'총 시장 이익',
  e_today:'오늘의 수입',
  t_level:'팀 레벨',
  w_cnt:'지갑 연결',
  w_scnt:'지갑이 연결되었습니다',
  i_invite:'초대',
  t_team:'팀',
  token1: token1,
  h_n1: "홈페이지",
  h_n2: "채굴",
  h_n3: "교환",
  h_n4: "시장",
  h_n5: "내",
  h_n6: "리더보드",
  home_n1: "총 잠금 금액",
  home_n2: "LBR 파괴",
  home_n4: "취급 수수료 USDT",
  home_n3: "LBR 가격",
  cwallet: "지갑 연결",
  langtype: "English",
  reward: '수확',
  nhsyl: "연환산 수익률",
  deposited: "잠금 위치",
  VL: "전체 잠금",
  lockDay: "잠금 기간",
  days: "天",
  goLock: "창고 잠금"+token1,
  back: "돌아가기",
  totalLock: "전체 잠금 위치",
  rcl: token1+"일일 출력",
  deposit1: "코인 입금",
  withdrawal1: "철회",
  wbalance: token1+"지갑 잔액:",
  avaliable: token1+" 보상:",
  lockTime: "잠금 해제 시간:",
  noLock: "잠금 해제된 창고",
  myLocked: "잠김:",
  max: "최대",
  bt_t: "참고:",
  bt_1_1: "1, 락업 "+token1+"는 담보 채굴 가능 ",
  bt_1_2: ";",
  bt_2_1: "2. 잠금 후 토큰은 ",
  bt_2_2: "나중에 자동으로 잠금 해제됨;",
  bt_3_1: "3. 새로운 잠금이 완료될 때마다 잠금 해제 시간은 비보안 잠금 해제 시간과 동일합니다.",
  bt_3_2: "금액은 가중 평균으로 계산됩니다.",
  bt_4: "4. 담보/상환 작업을 할 때마다 현재 수입 "+token1+"가 자동으로 지갑으로 이체됩니다.",


  withdrawal: "철회",
  approve: "승인",
  sygz: "이익",
  claim: "인출 소득",
  withdrawall: "모두 철회",
  iptPlace: "수량 입력",
  deposit: "예금",
  depositall: "모두 예금",
  balance: "균형",
  menu1: "홈",
  menu2: "머신건 풀",
  home_t1: "단일 통화 담보 채굴",
  home_t2: "LP 서약 채굴",
  home_seemore: "더 보기",
  mining: "내 광산으로 이동",
  home_icon1_text: "고수익",
  home_icon2_text: "스마트 매칭",
  home_icon3_text: "위험 회피",
  home_icon4_text: "저장 및 검색",


  all:'모두',
  my:'나',

  start: "시작",
  partner: "파트너",
  sjjg: "감사 조직",
  approve_ok: "승인에 성공했습니다. 계속 진행하십시오!",
  f_lv: "4월",
  op_wk: "채굴",
  fmd_op1: "보상 받기",
  fmd_op2: "종료: 보상 받기 및 잠금 해제",
  error_tips_unconnect: "MetaMask 지갑을 열고 계정을 연결하세요!",
  error_tips_num0: "0보다 큰 숫자를 입력해야 합니다!",
  more_than_deposit: "출금 금액이 입금 금액보다 많습니다!",
  error_tips_claim: "청구할 보상이 없습니다!",
  error_tips_trans: "전환 가능한 토큰이 없습니다!",
  ok_tips_deposit: "입금 성공!",
  ok_tips_withdraw: "추출 성공!",
  ok_tips_claim: "성공적으로 보상을 요청하세요!",
  ok_tips_claim_exit: "종료: 보상 청구 및 해제",
  notmainnet_title: "경고",
  notmainnet_tips: "현재 탐색 중인 데이터는 메인 네트워크가 아닙니다. 지갑을 메인 네트워크로 전환하세요!",
  no_main_tips: "네트워크 오류, BSC 메인넷에 연결되어 있는지 확인하십시오!",
  no_metamask_tips: "메타마스크 지갑 플러그인을 설치하지 않았습니다!",
  catch_err: "네트워크 예외",
  footer1:'감사',
  sjurl:'https://wfcbsc.com/depfilm/audit.pdf',
  footer2:'트위터',
  footer3:'전보',
  lp: "LP 채굴",
  db: "단일 통화 마이닝",
  invite_text: "초대 링크",
  //nft
  enterNUM: "번호를 입력하세요",
  buy: "구매",
  num: "번호:",
  price: "가격(WFC):",
  s_all: "모두",
  s_sale: "판매 가능",
  s_unsale: "판매 취소",
  s_status: "상태:",
  sale_price: "판매가(WFC)",
  saleBack: "재구매",
  setSale: "판매 가능한 상태로 설정",
  setUnsale: "판매 취소 설정",
  go: "점프",
  prev: "이전 페이지",
  next: "다음 페이지",
  Opera_ok: "작업 성공!",
  number_error: "정확한 번호를 입력하세요!",
  no_nft: "아직 NFT가 없으시다면 먼저 구매하세요!",
  no_own: "이 번호의 NFT가 없습니다. 모두 확인하세요!",
  price_error: "정확한 가격을 입력하세요!",

  Slippage_tolerance:'변위 허용 오차',
  Transaction_deadline:'거래 마감',
  min_swap:'분',
  Interface_Settings:'인터페이스 설정',
  Toggle_Audio_Mode:'오디오 모드 전환',
  swap_on:'켜기',
  swap_off:'끄기',

  l_copy:'복사 성공',
  l_copyf:'복사에 실패했습니다. 다시 시도하십시오! ',
  l_upper:'상위 레벨 주소가 존재하지 않습니다',
  l_addrror:'연결된 지갑 주소는 상위 주소와 동일합니다',
  l_numerror:'입력한 양이 잘못되었습니다',
  l_stockvalue:'예금 가치는 미화 100달러보다 커야 합니다.',

  l_noprofit:'현재 인출할 이익이 없습니다',
  l_unprofit:'모금 가능',
  l_unfinished:'미완성',
  l_completed:'완료',
  l_teamlink:'검색 링크',
  l_enterrightaddress:'올바른 지갑 주소를 입력하세요',
  l_noTeamBelowInfo:'이 팀에 대한 하위 정보가 없습니다',
  l_deposit_desc:'예금은 가치를 더할 수 있습니다',
  l_sureIt:'확인',
  l_konwIt:'알았어요',
  l_widthing:'추출',
  l_innering:'입금',
  l_duiing:'확인 중',
  l_numing:'숫자',
  l_you:'「당신은 얻을 것이다',
  l_maxa:'최',
  l_ming:'디테일',
  l_swapt:'상환 확인',
  l_swapm:`거래가 출력되면 최소 {0}{1}를 받게 됩니다. 그렇지 않으면 거래가 재개됩니다.`,
  l_next:'다음',
  l_swaps:'{0}{1}을(를) 사용하여 {2}{3} 교환',
  l_swapb:'지갑에서 거래 확인',
  l_success:'제출 된',
  swap_setting:'스왑 설정',
  l_invite:'초대',
  l_fee:'취급 수수료',
  l_fee_tip1:'입금 시간> 30일, 수수료 2% 필요',
  l_fee_tip2:'입금 시간 <=30일, 수수료 5% 필요',


  l_error_upper:'상위 레벨 주소가 잘못되었습니다',
  l_error_log_1:'서비스 오류',
   l_error_log_2:'알 수 없는 오류',
   l_error_log_3:'팀 관계가 잘못되었습니다',
   l_error_log_4:'상위 주소가 잘못되었습니다',
   l_error_log_5:'상위 레벨 잔액($1보다 커야 함)',
   l_error_log_6:'지갑 잔고(천칭자리)가 부족합니다',
   l_error_log_7:'지갑 잔고(usdt)가 부족합니다',
   l_error_log_8:'총 입금액은 $100보다 커야 합니다',
   l_error_log_9:'상위 레벨 잔액($1보다 커야 함)',
   l_error_log_10:'저장된 레코드 없음',
   l_error_log_11:'잔액 부족',
   l_error_log_12:'거부됨',
   l_error_log_13:'불충분한 처리 수수료',
}