var token1 = 'WFC';

export const l = {
  t_isbottom:'已是底部',
  t_loadMore:'点击加载更多',
  t_loading:'加载中...',
  t_MinPA:'最低金额',
  t_Price:'价格',
  t_to:'到',
  t_from:'从',
  t_Duic:'兑换',
  t_SWAP:'交易',
  t_approving:'授权中...',
  t_cuntip:'存入比例',
  t_value:'金额',
  t_home3:'帮助用户获得更高的回报。',
  t_home2:'多个 DeFi 协议中找到高收益项目',
  t_home1:'支持多种 DeFi 协议。',
  t_tre:'团队收益',
  t_ttt:'团队业绩',
  t_num:'团队人数',
  t_info:'团队信息',
  t_desc1:'达到该级别可享受的团队收益比例为 ',
  t_desc:'需要团队业绩',
  t_todayp:'今日收益',
  t_tolp:'总收益',
  t_abd:'交易记录',
  t_wde:'提取记录',
  t_depD:'存入记录',
  t_profitD:'收益记录',
  t_int:'邀请',
  t_tolIn:'总收益',
  t_tolOut:'总提取',
  t_tolOne:'总计',
  t_de:'详情',
  t_jiedata:'结算日期',
  t_dedata:'存入时间',
  t_withdrawel:'提现',
  t_totalWith:'提现总额',
  t_servicege:'手续费',
  t_transA:'提取数量',
  t_transamount:'交易金额',
  t_transdate:'交易日期',
  t_deposit:'存入数量',
  t_profit:'市场总收益',
  e_today:'今日收益',
  t_level:'团队等级',
  w_cnt:'连接钱包',
  w_scnt:'钱包已连接',
  i_invite:'邀请',
  t_team:'团队',
  token1:token1,
  h_n1 : "首页",
  h_n2 : "挖矿",
  h_n3 : "兑换",
  h_n4 : "市场",
  h_n5 : "我的",
  h_n6: "排行榜",
  home_n1: "总锁仓金额",
  home_n2: "DOP 价格",
  home_n3: "LBR 价格",
  cwallet: "连接钱包",
  langtype: "English",
  reward: '收获',
  nhsyl: "年化收益率",
  deposited: "你的锁仓",
  VL: "总锁仓",
  lockDay: "锁仓期",
  days: "天",
  goLock: "锁仓 "+token1,
  back: "返回",
  totalLock: "总锁仓",
  rcl: token1+"日产量",
  deposit1: "存币",
  withdrawal1: "提币",
  wbalance: token1+"钱包余额：",
  avaliable: token1+" 奖励：",
  lockTime: "解锁时间：",
  noLock: "未锁仓",
  myLocked: "已锁仓：",
  max: "最大",
  bt_t: "注意：",
  bt_1_1: "1、锁仓 "+token1+" 可获得用于质押挖矿的 ",
  bt_1_2: "；",
  bt_2_1: "2、锁仓后，您的代币将在 ",
  bt_2_2: " 日后自动解锁；",
  bt_3_1: "3、每次新的一笔锁仓完成，解锁时间将与未抵押的 ",
  bt_3_2: " 数额进行加权平均计算。",
  bt_4: "4、您每次的质押/赎回操作，当前所得 "+token1+" 都会自动转到您的钱包。",

  yesterday: "昨日",
  today: "今日",
  week: "周榜",
  month: "月榜",
  ranking_t: "分红数量排行榜",
  ranking_t1: "排名",
  ranking_t2: "钱包地址",
  ranking_t3: "分红数量",
  nodata: "暂无更多数据",
  ranking_tips1: "分红前50名将按比例获得249个"+token1,
  ranking_tips2: "分红前50名将按比例获得1743个"+token1,
  ranking_tips3: "分红前50名将按比例获得7290个"+token1,


  withdrawal: "提取",
  approve: "授权",
  sygz: "收益",
  claim: "提取收益",
  withdrawall: "提取全部",
  iptPlace: "输入数量",
  deposit: "存入",
  depositall: "存入全部",
  balance: "余额",
  menu1: "首页",
  menu2: "机枪池",
  home_t1: "单币质押挖矿",
  home_t2: "LP质押挖矿",
  home_seemore: "更多..",
  mining: "去挖矿",
  home_icon1_text: "高收益",
  home_icon2_text: "智能配资",
  home_icon3_text: "风险对冲",
  home_icon4_text: "随存随取",


  all: '全部',
  my: '我的',

  start: "开始",
  partner: "合作伙伴",
  sjjg: "审计机构",
  approve_ok: "授权成功，请继续操作！",
  f_lv: "APR",
  op_wk: "挖矿",
  fmd_op1: "领取奖励",
  fmd_op2: "退出：领取奖励 & 解押",
  error_tips_unconnect: "请打开MetaMask钱包，并连接您的账户！",
  error_tips_num0: "您必须输入一个大于0的数字！",
  more_than_deposit: "提取数量大于已存入的数量！",
  error_tips_claim: "您还没有可领取的奖励！",
  error_tips_trans: "您还没有可转换的代币！",
  ok_tips_deposit: "存入成功！",
  ok_tips_withdraw: "提取成功！",
  ok_tips_claim: "领取奖励成功！",
  ok_tips_claim_exit: "退出：领取奖励 & 解押",
  notmainnet_title: "警告",
  notmainnet_tips: "您当前浏览的数据不是来自于主网络，请切换您的钱包到主网络！",
  no_main_tips: "网络错误，请确认您连接的是 BSC mainnet!",
  no_metamask_tips: "您还没有安装MetaMask钱包插件！",
  catch_err: "网络异常",
  footer1 : '审计',
  sjurl: 'https://wfcbsc.com/depfilm/audit.pdf',
  footer2 : '推特',
  footer3 : '电报',
  lp:"LP挖矿",
  db:"单币挖矿",
  invite_text: "邀请链接",
  //nft
  enterNUm: "请输入编号",
  buy: "购买",
  num: "编号：",
  price: "价格(WFC)：",
  s_all: "全部",
  s_sale: "可卖",
  s_unsale: "不可卖",
  s_status: "状态：",
  sale_price: "卖出价格(WFC)",
  saleBack: "回购",
  setSale: "设为可卖",
  setUnsale: "设为禁卖",
  go: "跳转",
  prev: "上一页",
  next: "下一页",
  operate_ok: "操作成功！",
  number_error: "请输入正确的编号！",
  no_nft: "您还没有拥有NFT，请先去购买！",
  no_own: "您还没有此编号的NFT，请去全部里查询！",
  price_error: "请输入正确的价格！",

  Slippage_tolerance:'位移公差',
  Transaction_deadline:'交易截止时间',
  minute_swap:'分钟',
  Interface_Settings:'接口设置',
  Toggle_Audio_Mode:'切换音频模式',
  swap_on:'开',
  swap_off:'关',

  l_copy:'复制成功',
  l_copyf:'复制失败,请重试！',
  l_upper:'上级地址不存在',
  l_addrror:'连接钱包地址与上级地址相同',
  l_numerror:'输入数量错误',
  l_stockvalue:'存入存入价值需大于100美金',

  l_noprofit:'当前您暂无可提收益',
  l_unprofit:'可提',
  l_unfinished:'未完成',
  l_completed:'已完成',
  l_teamlink:'搜索链接',
  l_enterrightaddress:'请输入正确钱包地址',
  l_noTeamBelowInfo:'暂无该团队下级信息',
  l_deposit_desc:'存入可以增值',
  l_sureIt:'确认',
  l_konwIt:'知道了',
  l_widthing:'提取中',
  l_innering:'存入中',
  l_duiing:'确认中',
  l_numing:'数量',
  l_you:'你将获得',
  l_maxa:'最大',
  l_ming:'明细',
  l_swapt:'确认兑换',
  l_swapm:'如果交易输出，您将收到至少{0}{1}，否则交易将恢复',
  l_next:'下一步',
  l_swaps:'用 {0}{1} 兑换 {2}{3}',
  l_swapb:'确认在钱包中交易',
  l_success:'已提交',
  swap_setting:'交易设置',
  l_invite:'邀请',

  l_error_upper:'上级地址不正确',
  l_error_log_1:'服务错误',
  l_error_log_2:'未知错误',
  l_error_log_3:'团队关系不正确',
  l_error_log_4:'上级地址不正确',
  l_error_log_5:'上级余额 （必须 大于 1美元 ）',
  l_error_log_6:'钱包余额 （libra）不足',
  l_error_log_7:'钱包余额 （usdt）不足',
  l_error_log_8:'存入总价值需大于 100美金',
  l_error_log_9:'上级余额 （必须 大于 1美元 ）',
  l_error_log_10:'没有存入记录',
  l_error_log_11:'余额不足',
  l_error_log_12:'已拒绝',
}